// ── JI Scale Data (41-EDO Pythagorean + 53-EDO Schismatic) ────────────────
//
// Step values for the 19 curated JI scales the Tonal Audiation tabs
// expose under Pythagorean and Schismatic temperaments.  Each scale's
// degree → step map is computed from the underlying just-intonation
// ratios converted to the nearest integer step in 41-EDO and 53-EDO.
//
// The names here match the public tonality identifiers in
// jiTonalityFamilies.ts.  A module-load side-effect registers these maps
// with edoData.ts so getModeDegreeMap() returns them, mirroring how the
// septimal/neutral/etc. xen families are wired in for 31-EDO.
//
// Where multiple JI ratios round to the same EDO step, we pick the
// theoretically-cleaner ratio (e.g. 5/4 over 81/64 for the 5-limit M3).
// 41-EDO and 53-EDO both round these consistently — the differences in
// chord/scale character come from elsewhere.

import { registerXenPatternMaps } from "./edoData";
import { registerScaleCents } from "./jiChordAnalysis";

type ModeMap = Record<string, number>;
type ScaleFamilyMap = Record<string, ModeMap>;

// ── JI Scale catalog ─────────────────────────────────────────────────────
//
// Each entry lists [degree-label, ratio-cents] tuples.  We compute the
// EDO-specific step at scale-build time by rounding cents to the nearest
// step.  Keeping the cents alongside the labels makes the music-theory
// intent traceable; if a ratio later needs adjusting, the change is in
// one place.
//
// Cents reference (for grep / sanity-check):
//   1/1     0          12/11   150.6      14/9    764.9
//   16/15   111.7      11/9    347.4      8/5     813.7
//   10/9    182.4      5/4     386.3      18/11   852.6
//   9/8     203.9      81/64   407.8      5/3     884.4
//   7/6     266.9      4/3     498.0      27/16   905.9
//   32/27   294.1      11/8    551.3      12/7    933.1
//   6/5     315.6      45/32   590.2      7/4     968.8
//                      7/5     582.5      16/9    996.1
//                      729/512 611.7      9/5     1017.6
//                      3/2     701.96     11/6    1049.4
//                                         15/8    1088.3
//                                         243/128 1109.8

interface JiScaleSpec {
  name: string;
  /** [degree label, cents] tuples sorted ascending by cents. */
  steps: [string, number][];
}

const JI_SCALES: JiScaleSpec[] = [
  // ── 3-LIMIT (Pythagorean) ────────────────────────────────────────────
  // Generated by stacks of pure 3:2 fifths; thirds are 81/64 (Pyth M3) or
  // 32/27 (Pyth m3).
  { name: "Pythagorean Ionian",
    steps: [["1",0],["2",203.9],["3",407.8],["4",498.0],["5",702.0],["6",905.9],["7",1109.8]] },
  { name: "Pythagorean Aeolian",
    steps: [["1",0],["2",203.9],["b3",294.1],["4",498.0],["5",702.0],["b6",792.2],["b7",996.1]] },
  { name: "Pythagorean Dorian",
    steps: [["1",0],["2",203.9],["b3",294.1],["4",498.0],["5",702.0],["6",905.9],["b7",996.1]] },
  { name: "Pythagorean Mixolydian",
    steps: [["1",0],["2",203.9],["3",407.8],["4",498.0],["5",702.0],["6",905.9],["b7",996.1]] },

  // ── 5-LIMIT (Just Intonation) ────────────────────────────────────────
  // Pure 5/4 thirds; modes use the "tonally-pure" form where each mode's
  // tonic has a true 3/2 fifth (so the 2nd of Dorian is 10/9, not 9/8 —
  // avoids the wolf 5th that mode-of-Ionian-via-rotation would introduce).
  { name: "JI Ionian",
    steps: [["1",0],["2",203.9],["3",386.3],["4",498.0],["5",702.0],["6",884.4],["7",1088.3]] },
  { name: "JI Dorian",
    steps: [["1",0],["2",182.4],["b3",315.6],["4",498.0],["5",702.0],["6",884.4],["b7",1017.6]] },
  { name: "JI Phrygian",
    steps: [["1",0],["b2",111.7],["b3",315.6],["4",498.0],["5",702.0],["b6",813.7],["b7",1017.6]] },
  { name: "JI Lydian",
    steps: [["1",0],["2",203.9],["3",386.3],["#4",590.2],["5",702.0],["6",884.4],["7",1088.3]] },
  { name: "JI Mixolydian",
    steps: [["1",0],["2",203.9],["3",386.3],["4",498.0],["5",702.0],["6",884.4],["b7",1017.6]] },
  { name: "JI Aeolian",
    steps: [["1",0],["2",203.9],["b3",315.6],["4",498.0],["5",702.0],["b6",813.7],["b7",1017.6]] },
  { name: "JI Harmonic Minor",
    steps: [["1",0],["2",203.9],["b3",315.6],["4",498.0],["5",702.0],["b6",813.7],["7",1088.3]] },

  // ── 7-LIMIT (Septimal) ───────────────────────────────────────────────
  // Adds 7/4 (harmonic 7th, ~969¢), 7/6 (subminor 3rd, ~267¢),
  // 7/5 (septimal tritone, ~583¢).  Garibaldi[7] is the 7-note MOS
  // generated by the 4/3 generator in 41-EDO (and same in 53-EDO).
  { name: "Garibaldi",
    // 41-EDO: stacks of 17\41 mod 41 → sorted [0,3,10,17,20,27,34]
    // 53-EDO: stacks of 22\53 mod 53 → sorted [0,4,13,22,26,35,44]
    // Cents here are taken from the 41-EDO realisation; 53-EDO rounds the
    // same chromatic positions to its own grid via the catalog mechanism.
    steps: [["1",0],["b2",87.8],["b3",292.7],["4",497.6],["#4",585.4],["b6",790.2],["b7",995.1]] },
  { name: "Septimal Major",
    steps: [["1",0],["2",203.9],["3",386.3],["4",498.0],["5",702.0],["6",884.4],["b7",968.8]] },
  { name: "Septimal Minor",
    steps: [["1",0],["2",203.9],["b3",266.9],["4",498.0],["5",702.0],["b6",813.7],["b7",968.8]] },
  { name: "Septimal Diminished",
    steps: [["1",0],["2",203.9],["b3",266.9],["4",498.0],["b5",582.5],["b6",813.7],["b7",968.8]] },

  // ── 11-LIMIT (Neutral / Maqam) ───────────────────────────────────────
  // Adds 11/9 (neutral 3rd, ~347¢), 11/8 (wide 4th, ~551¢), 12/11
  // (neutral 2nd, ~151¢).  Mohajira is the canonical neutral diatonic
  // (LsLsLsL where s is a neutral 2nd).  The Maqam scales mix neutral
  // intervals with diatonic ones in the patterns that define each maqam.
  { name: "Mohajira",
    steps: [["1",0],["b2",150.6],["b3",347.4],["4",498.0],["5",702.0],["b6",852.6],["b7",1049.4]] },
  { name: "Maqam Rast",
    steps: [["1",0],["2",203.9],["b3",347.4],["4",498.0],["5",702.0],["6",905.9],["b7",1049.4]] },
  { name: "Maqam Bayati",
    steps: [["1",0],["b2",150.6],["b3",315.6],["4",498.0],["5",702.0],["b6",813.7],["b7",1017.6]] },
  { name: "Maqam Hijaz",
    // Two augmented seconds — characteristic Hijaz "exotic" sound.
    steps: [["1",0],["b2",111.7],["3",386.3],["4",498.0],["5",702.0],["b6",813.7],["b7",996.1]] },
  // Additional 11-limit Maqamat — both feature the 11/8 wide 4th or
  // 11-prime-derived intervals that don't reduce cleanly to lower limits.
  { name: "Maqam Saba",
    // Saba's hallmark is the dropped 4th (here 11/8 wide instead of 4/3)
    // creating an unstable, longing colour.  Common in Iraqi / Egyptian Maqam.
    steps: [["1",0],["2",203.9],["b3",315.6],["#4",551.3],["5",702.0],["b6",813.7],["b7",1017.6]] },
  { name: "Maqam Huzam",
    // Built on Sikah; uses a neutral 3rd (11/9) and a wide minor 6th (11/7).
    steps: [["1",0],["b2",165.0],["b3",347.4],["4",498.0],["5",702.0],["b6",782.5],["b7",1017.6]] },

  // ── 13-LIMIT (Tridecimal) ────────────────────────────────────────────
  // Adds 13/8 (~840¢, wide neutral 6), 13/11 (~289¢, supraminor 3rd),
  // 16/13 (~359¢, low neutral 3rd).  Most musically meaningful in the
  // 6th-degree position — Tridecimal Major's 6 lands between 5/3 and
  // 27/16 in a place that doesn't exist in 5-limit at all.
  { name: "Tridecimal Major",
    steps: [["1",0],["2",203.9],["3",386.3],["4",498.0],["5",702.0],["6",840.5],["7",1088.3]] },
  { name: "Tridecimal Minor",
    // 13/11 m3 + 13/8 b6 — the m3 and b6 share a 13-prime kinship that
    // makes this a coherent "tridecimal minor" rather than just a
    // 5-limit minor with one altered note.
    steps: [["1",0],["2",203.9],["b3",289.2],["4",498.0],["5",702.0],["b6",840.5],["b7",996.1]] },
  { name: "Maqam Sikah",
    // The neutral 3rd / 6th Maqam family Sikah belongs to.  In 13-limit
    // the b3 (16/13 ≈ 359¢) sits a touch lower than the 11-limit
    // neutral 3rd (11/9 ≈ 347¢), giving a darker, more melodic colour.
    steps: [["1",0],["2",203.9],["b3",359.5],["4",498.0],["5",702.0],["b6",840.5],["b7",1049.4]] },

  // ── 17-LIMIT (Heptadecimal) ──────────────────────────────────────────
  // 17/16 (~105¢) sits between the just minor 2nd (16/15 ≈ 112¢) and
  // pure unison.  Useful as a "small leading-tone" in scales where the
  // 5-limit b2 feels too wide.  41-EDO approximates 17/16 cleanly.
  { name: "Heptadecimal",
    // 17/16 b2, 5-limit core in the middle, 17/9 leading tone.
    steps: [["1",0],["b2",105.0],["3",386.3],["4",498.0],["5",702.0],["6",884.4],["7",1101.0]] },

  // ── 19-LIMIT (Nonadecimal) ───────────────────────────────────────────
  // 19/16 (~298¢) is fractionally below the Pythagorean m3 (32/27 ≈ 294¢)
  // and the 5-limit m3 (6/5 ≈ 316¢) — its own colour rather than just
  // an approximation of either.  Distinctive in 41-EDO.
  { name: "Nonadecimal Minor",
    steps: [["1",0],["2",203.9],["b3",297.5],["4",498.0],["5",702.0],["b6",813.7],["b7",996.1]] },

  // ── 23 / 29 / 31-LIMIT (demonstrative) ───────────────────────────────
  // No established repertoire uses these primes as a scale's organising
  // principle — they're included so the user can audition each prime's
  // characteristic interval colour.  Each scale anchors a 5-limit
  // diatonic spine and substitutes one or two degrees with the higher-
  // prime version (e.g. 23/19 in place of the 6/5 minor third).  41-EDO
  // approximates 23 well, 29 / 31 less so but still distinguishable.
  { name: "23-Limit Demo",
    // 23/19 (~329¢) supraminor 3rd + 23/14 (~859¢) wide minor 6th.
    steps: [["1",0],["2",203.9],["b3",329.2],["4",498.0],["5",702.0],["6",859.4],["b7",996.1]] },
  { name: "29-Limit Demo",
    // Anchored on the diatonic 2 / 4 / 5 spine; 29-prime colour at b3
    // (29/24 ≈ 328¢) and b6 (29/18 ≈ 770¢) so the scale walks like a
    // recognisable minor with two notes shifted into 29-territory.
    steps: [["1",0],["2",203.9],["b3",327.6],["4",498.0],["5",702.0],["b6",770.5],["b7",1029.6]] },
  { name: "31-Limit Demo",
    // Same diatonic 2 / 4 / 5 spine; 31-prime colour at b3 (31/26 ≈ 338¢)
    // and b6 (31/20 ≈ 766¢) — sounds like a minor scale tilted into a
    // distinct 31-flavour without abandoning its tonal centre.
    steps: [["1",0],["2",203.9],["b3",338.0],["4",498.0],["5",702.0],["b6",765.5],["b7",895.7]] },
];

// ── Build per-EDO ScaleFamilyMaps ────────────────────────────────────────
//
// edoData's getModeDegreeMap looks up scales as
//   maps[scaleFam]?.[modeName]
// so we group every JI scale under one synthetic family per EDO ("JI
// Family") and key by the scale's display name.  The bank/picker code in
// jiTonalityFamilies.ts surfaces them through the limit groups; the
// underlying lookup just needs the map.

const JI_FAMILY_NAME = "JI Family";

function centsToStep(cents: number, edo: number): number {
  return Math.round((cents / 1200) * edo);
}

function buildJiScalesForEdo(edo: number): ScaleFamilyMap {
  const fam: Record<string, ModeMap> = {};
  for (const scale of JI_SCALES) {
    const map: ModeMap = {};
    for (const [degLabel, cents] of scale.steps) {
      map[degLabel] = centsToStep(cents, edo);
    }
    fam[scale.name] = map;
  }
  return { [JI_FAMILY_NAME]: fam };
}

// ── Module-load registration ────────────────────────────────────────────
// Side-effect: hooks the JI families into edoData's pattern-map cache so
// getModeDegreeMap(41, "JI Family", "Pythagorean Ionian") returns the
// degree map without any further wiring.  Mirrors the 31-EDO xen
// registration in musicTheory.ts.

registerXenPatternMaps(41, buildJiScalesForEdo(41));
registerXenPatternMaps(53, buildJiScalesForEdo(53));

// Cent-value side-channel for the chord analyzer — avoids a circular
// import by letting jiChordAnalysis.ts pull the underlying cents
// without re-importing JI_SCALES.
for (const scale of JI_SCALES) {
  registerScaleCents(scale.name, scale.steps.map(([, c]) => c));
}

// ── Public helpers ──────────────────────────────────────────────────────

/** Family name used for all JI scales (single bucket per EDO). */
export const JI_FAMILY = JI_FAMILY_NAME;

/** Flat list of every JI scale name in catalog order. */
export const JI_SCALE_NAMES: string[] = JI_SCALES.map(s => s.name);

/** Steps for a JI scale in a given EDO, sorted ascending. */
export function getJiScaleSteps(edo: number, scaleName: string): number[] | null {
  const spec = JI_SCALES.find(s => s.name === scaleName);
  if (!spec) return null;
  return spec.steps.map(([, cents]) => centsToStep(cents, edo));
}

/** Degree labels for a JI scale, in scale order. */
export function getJiScaleDegrees(scaleName: string): string[] | null {
  const spec = JI_SCALES.find(s => s.name === scaleName);
  if (!spec) return null;
  return spec.steps.map(([deg]) => deg);
}
