// ── JI Scale Data (41-EDO Pythagorean + 53-EDO Schismatic) ────────────────
//
// Step values for the 19 curated JI scales the Tonal Audiation tabs
// expose under Pythagorean and Schismatic temperaments.  Each scale's
// degree → step map is computed from the underlying just-intonation
// ratios converted to the nearest integer step in 41-EDO and 53-EDO.
//
// The names here match the public tonality identifiers in
// jiTonalityFamilies.ts.  A module-load side-effect registers these maps
// with edoData.ts so getModeDegreeMap() returns them, mirroring how the
// septimal/neutral/etc. xen families are wired in for 31-EDO.
//
// Where multiple JI ratios round to the same EDO step, we pick the
// theoretically-cleaner ratio (e.g. 5/4 over 81/64 for the 5-limit M3).
// 41-EDO and 53-EDO both round these consistently — the differences in
// chord/scale character come from elsewhere.

import { registerXenPatternMaps } from "./edoData";
import { registerScaleCents } from "./jiChordAnalysis";

type ModeMap = Record<string, number>;
type ScaleFamilyMap = Record<string, ModeMap>;

// ── JI Scale catalog ─────────────────────────────────────────────────────
//
// Each entry lists [degree-label, ratio-cents] tuples.  We compute the
// EDO-specific step at scale-build time by rounding cents to the nearest
// step.  Keeping the cents alongside the labels makes the music-theory
// intent traceable; if a ratio later needs adjusting, the change is in
// one place.
//
// Cents reference (for grep / sanity-check):
//   1/1     0          12/11   150.6      14/9    764.9
//   16/15   111.7      11/9    347.4      8/5     813.7
//   10/9    182.4      5/4     386.3      18/11   852.6
//   9/8     203.9      81/64   407.8      5/3     884.4
//   7/6     266.9      4/3     498.0      27/16   905.9
//   32/27   294.1      11/8    551.3      12/7    933.1
//   6/5     315.6      45/32   590.2      7/4     968.8
//                      7/5     582.5      16/9    996.1
//                      729/512 611.7      9/5     1017.6
//                      3/2     701.96     11/6    1049.4
//                                         15/8    1088.3
//                                         243/128 1109.8

interface JiScaleSpec {
  name: string;
  /** [degree label, cents] tuples sorted ascending by cents. */
  steps: [string, number][];
}

const JI_SCALES: JiScaleSpec[] = [
  // ── 3-LIMIT (Pythagorean) ────────────────────────────────────────────
  // Generated by stacks of pure 3:2 fifths; thirds are 81/64 (Pyth M3) or
  // 32/27 (Pyth m3).
  { name: "Pythagorean Ionian",
    steps: [["1",0],["2",203.9],["3",407.8],["4",498.0],["5",702.0],["6",905.9],["7",1109.8]] },
  { name: "Pythagorean Aeolian",
    steps: [["1",0],["2",203.9],["b3",294.1],["4",498.0],["5",702.0],["b6",792.2],["b7",996.1]] },
  { name: "Pythagorean Dorian",
    steps: [["1",0],["2",203.9],["b3",294.1],["4",498.0],["5",702.0],["6",905.9],["b7",996.1]] },
  { name: "Pythagorean Mixolydian",
    steps: [["1",0],["2",203.9],["3",407.8],["4",498.0],["5",702.0],["6",905.9],["b7",996.1]] },

  // ── 5-LIMIT (Just Intonation) ────────────────────────────────────────
  // Pure 5/4 thirds; modes use the "tonally-pure" form where each mode's
  // tonic has a true 3/2 fifth (so the 2nd of Dorian is 10/9, not 9/8 —
  // avoids the wolf 5th that mode-of-Ionian-via-rotation would introduce).
  { name: "JI Ionian",
    steps: [["1",0],["2",203.9],["3",386.3],["4",498.0],["5",702.0],["6",884.4],["7",1088.3]] },
  { name: "JI Dorian",
    steps: [["1",0],["2",182.4],["b3",315.6],["4",498.0],["5",702.0],["6",884.4],["b7",1017.6]] },
  { name: "JI Phrygian",
    steps: [["1",0],["b2",111.7],["b3",315.6],["4",498.0],["5",702.0],["b6",813.7],["b7",1017.6]] },
  { name: "JI Lydian",
    steps: [["1",0],["2",203.9],["3",386.3],["#4",590.2],["5",702.0],["6",884.4],["7",1088.3]] },
  { name: "JI Mixolydian",
    steps: [["1",0],["2",203.9],["3",386.3],["4",498.0],["5",702.0],["6",884.4],["b7",1017.6]] },
  { name: "JI Aeolian",
    steps: [["1",0],["2",203.9],["b3",315.6],["4",498.0],["5",702.0],["b6",813.7],["b7",1017.6]] },
  { name: "JI Harmonic Minor",
    steps: [["1",0],["2",203.9],["b3",315.6],["4",498.0],["5",702.0],["b6",813.7],["7",1088.3]] },

  // ── 7-LIMIT (Septimal) ───────────────────────────────────────────────
  // Per direct user direction (2026-05-04): a higher-limit scale must
  // carry its named prime at the 3rd, 6th, and 7th — otherwise it is
  // not faithfully representing that prime limit and is removed.  No
  // 7-limit scale in the previous catalog cleanly satisfied 3-6-7 in
  // 7-prime (Garibaldi's 3-6-7 are Pythagorean; Septimal Major's 3
  // and 6 are 5-limit; Septimal Minor's b6 is 5-limit; etc.).  The
  // 7-LIMIT family is therefore empty pending a future curated scale
  // whose 3rd / 6th / 7th all use 7-prime ratios.

  // ── 11-LIMIT (Neutral) ───────────────────────────────────────────────
  // Adds 11/9 (neutral 3rd, ~347¢), 11/8 (wide 4th, ~551¢), 12/11
  // (neutral 2nd, ~151¢).  Mohajira is the canonical neutral diatonic
  // (LsLsLsL where s is a neutral 2nd) and is the only 11-limit scale
  // whose 3rd, 6th, and 7th are all 11-prime — every Maqam variant
  // mixes 5-limit / 3-limit tones at one of those positions and was
  // removed under the 3-6-7 prime-purity rule.
  { name: "Mohajira",
    steps: [["1",0],["b2",150.6],["b3",347.4],["4",498.0],["5",702.0],["b6",852.6],["b7",1049.4]] },

  // ── 13-LIMIT (Tridecimal) ────────────────────────────────────────────
  // Per direct user direction (2026-05-04): a "13-limit" scale must
  // carry the 13-prime at its 3rd, 6th, and 7th positions — that is
  // what marks it as a faithful 13-limit scale rather than a 5-limit
  // cousin.  Scales that preserve canonical 9/8 / 4/3 / 3/2 at 2 / 4 /
  // 5 carry "Diatonic" in their name to flag the diatonic backbone;
  // the higher-prime colour is in the modal-defining 3-6-7 only.
  // Key 13-prime intervals: 13/12 (138¢), 13/11 (289¢ supraminor 3rd),
  // 13/10 (454¢ supermajor 3rd), 13/9 (637¢ aug-4th), 13/8 (841¢ wide
  // M6 / neutral 6), 13/7 (1072¢ subminor 7th).
  { name: "Tridecimal Diatonic Major",
    // 2 / 4 / 5 canonical (9/8, 4/3, 3/2) — the diatonic backbone.
    // 3 → 13/10 (454¢ supermajor 3rd), 6 → 13/8 (841¢), 7 → 13/7
    // (1072¢ — narrow M7 / wide subminor 7).  All three modal-
    // defining tones are 13-prime.
    steps: [["1",0],["2",203.9],["3",454.2],["4",498.0],["5",702.0],["6",840.5],["7",1071.7]] },
  { name: "Tridecimal Diatonic Minor",
    // 2 / 4 / 5 canonical.  b3 → 13/11, b6 → 13/8, b7 → 13/7 — every
    // minor-mode modal tone is 13-prime.
    steps: [["1",0],["2",203.9],["b3",289.2],["4",498.0],["5",702.0],["b6",840.5],["b7",1071.7]] },

  // ── 17-LIMIT (Heptadecimal) ──────────────────────────────────────────
  // Key 17-prime intervals: 17/16 (105¢ small leading-tone m2),
  // 17/14 (336¢ supraminor 3rd), 17/13 (464¢ wide M3), 17/12 (603¢
  // tritone), 17/11 (754¢ b6), 17/10 (919¢ wide M6), 17/9 (1101¢
  // wide M7).
  { name: "Heptadecimal Diatonic Major",
    // 2 / 4 / 5 canonical (9/8, 4/3, 3/2) — diatonic backbone.
    // 3 → 17/13 (464¢ wide M3 — 17 dominant, 13 in denominator),
    // 6 → 17/10, 7 → 17/9.  All three modal-defining tones carry
    // the 17-prime.
    steps: [["1",0],["2",203.9],["3",464.4],["4",498.0],["5",702.0],["6",918.6],["7",1101.0]] },
  { name: "Heptadecimal Minor",
    // 4 / 5 canonical; b2 → 17/16 displaces the canonical 9/8 so this
    // scale doesn't carry the "Diatonic" tag (the diatonic 2 isn't
    // preserved).  b3 → 17/14, b6 → 17/11, b7 → 17/10 — minor mode
    // with 17-prime saturation across b2 / b3 / b6 / b7.
    steps: [["1",0],["b2",105.0],["b3",336.1],["4",498.0],["5",702.0],["b6",753.6],["b7",918.6]] },

  // ── 19-LIMIT (Nonadecimal) ───────────────────────────────────────────
  // Key 19-prime intervals: 19/18 (94¢ small m2), 19/16 (298¢ m3),
  // 19/15 (409¢ wide M3), 19/13 (657¢ #4-area), 19/12 (795¢ b6-ish),
  // 19/11 (946¢ b7), 19/10 (1111¢ wide M7).
  { name: "Nonadecimal Diatonic Major",
    // 2 / 4 / 5 canonical — diatonic backbone.  3 → 19/15, 6 → 19/12
    // (795¢ — flat enough to read as b6, so this Major leans
    // Mixolydian-with-flat-6 / Phrygian-Major-ish territory), 7 →
    // 19/10.  All three modal-defining tones are 19-prime.
    steps: [["1",0],["2",203.9],["3",409.2],["4",498.0],["5",702.0],["b6",795.0],["7",1111.2]] },
  { name: "Nonadecimal Diatonic Minor",
    // 2 / 4 / 5 canonical.  b3 → 19/16, b6 → 19/12, b7 → 19/11.
    // Three 19-prime substitutions span the minor-mode modal palette.
    steps: [["1",0],["2",203.9],["b3",297.5],["4",498.0],["5",702.0],["b6",795.0],["b7",945.7]] },

  // ── 23 / 29 / 31-LIMIT (multi-prime higher-limit colour) ─────────────
  // Each scale carries 3-4 intervals from its named prime — enough that
  // the prime defines the modal colour, not just a single substituted
  // tone.  Major / Minor labels reflect the 1-3-5 chord quality at the
  // tonic so the I roman numeral renders as I (Major) or i (minor).
  // 41-EDO approximates each prime to within a few cents; 53-EDO is
  // accurate on 13 / 19 and weaker on 17 / 23 / 29 / 31, which is why
  // those scales aren't surfaced for 53-EDO in JI_LIMITS_PER_EDO.

  // 23-LIMIT  Key intervals: 23/22 (77¢ b2), 23/19 (329¢ supraminor 3),
  //          23/18 (424¢ wide M3), 23/14 (859¢ b6), 23/12 (1126¢
  //          extra-wide M7).  No clean 23-prime M6 or b7.
  { name: "Vicesimotertial Diatonic Major",
    // 2 / 4 / 5 canonical.  3 → 23/18 (424¢), 6 → 23/14 (859¢ —
    // reads as a Mixolydian-ish wide M6 / narrow b6), 7 → 23/12
    // (1126¢).  All three modal-defining tones carry the 23-prime.
    steps: [["1",0],["2",203.9],["3",424.4],["4",498.0],["5",702.0],["6",859.4],["7",1126.3]] },
  { name: "Vicesimotertial Diatonic Minor",
    // 2 / 4 / 5 canonical.  b3 → 23/19 (329¢ supraminor), b6 →
    // 23/14 (859¢), b7 → 23/13 (988¢).  Three 23-foregrounded tones
    // span the minor-mode modal palette.
    steps: [["1",0],["2",203.9],["b3",329.2],["4",498.0],["5",702.0],["b6",859.4],["b7",987.7]] },
  // 29-LIMIT  Key intervals: 29/27 (124¢ small m2), 29/24 (328¢
  //          supraminor 3rd), 29/23 (401¢ wide M3), 29/18 (770¢ b6),
  //          29/17 (871¢ M6), 29/16 (1030¢ b7).  No clean 29-prime M7
  //          — Major-mode 7 falls back to 15/8 OR Major adopts a
  //          Mixolydian b7 to fit a 29-prime tone there.
  { name: "Vicenovenal Diatonic Major",
    // 2 / 4 / 5 canonical.  3 → 29/23 (401¢ wide M3), 6 → 29/17
    // (871¢), b7 → 29/16 (1030¢, Mixolydian-leaning).  Three 29-prime
    // tones at the modal-defining 3rd / 6th / 7th positions.
    steps: [["1",0],["2",203.9],["3",401.3],["4",498.0],["5",702.0],["6",871.4],["b7",1029.6]] },
  { name: "Vicenovenal Diatonic Minor",
    // 2 / 4 / 5 canonical.  b3 → 29/24 (328¢), b6 → 29/18 (770¢),
    // b7 → 29/16 (1030¢).  Three 29-prime tones span the minor-mode
    // modal palette.
    steps: [["1",0],["2",203.9],["b3",327.6],["4",498.0],["5",702.0],["b6",770.5],["b7",1029.6]] },
  // 31-LIMIT  Key intervals: 31/29 (115¢ b2), 31/26 (336¢ supraminor 3),
  //          31/25 (372¢ neutral-leaning M3), 31/20 (765¢ b6),
  //          31/19 (905¢ M6), 31/17 (1010¢ b7), 31/16 (1145¢ extra-
  //          wide M7).
  { name: "Trigesimoprimal Diatonic Major",
    // 2 / 4 / 5 canonical.  3 → 31/25 (372¢, neutral-leaning M3 —
    // classified as major by the wider cent-zone classifier), 6 →
    // 31/19 (905¢), 7 → 31/16 (1145¢ extra-wide leading-tone).
    steps: [["1",0],["2",203.9],["3",371.6],["4",498.0],["5",702.0],["6",904.6],["7",1145.0]] },
  { name: "Trigesimoprimal Diatonic Minor",
    // 2 / 4 / 5 canonical.  b3 → 31/26 (336¢), b6 → 31/20 (765¢),
    // b7 → 31/17 (1010¢).  Three 31-prime tones span the minor-mode
    // modal palette.
    steps: [["1",0],["2",203.9],["b3",336.0],["4",498.0],["5",702.0],["b6",765.5],["b7",1010.4]] },
];

// ── Build per-EDO ScaleFamilyMaps ────────────────────────────────────────
//
// edoData's getModeDegreeMap looks up scales as
//   maps[scaleFam]?.[modeName]
// so we group every JI scale under one synthetic family per EDO ("JI
// Family") and key by the scale's display name.  The bank/picker code in
// jiTonalityFamilies.ts surfaces them through the limit groups; the
// underlying lookup just needs the map.

const JI_FAMILY_NAME = "JI Family";

function centsToStep(cents: number, edo: number): number {
  return Math.round((cents / 1200) * edo);
}

function buildJiScalesForEdo(edo: number): ScaleFamilyMap {
  const fam: Record<string, ModeMap> = {};
  for (const scale of JI_SCALES) {
    const map: ModeMap = {};
    for (const [degLabel, cents] of scale.steps) {
      map[degLabel] = centsToStep(cents, edo);
    }
    fam[scale.name] = map;
  }
  return { [JI_FAMILY_NAME]: fam };
}

// ── Module-load registration ────────────────────────────────────────────
// Side-effect: hooks the JI families into edoData's pattern-map cache so
// getModeDegreeMap(41, "JI Family", "Pythagorean Ionian") returns the
// degree map without any further wiring.  Mirrors the 31-EDO xen
// registration in musicTheory.ts.

registerXenPatternMaps(41, buildJiScalesForEdo(41));
registerXenPatternMaps(53, buildJiScalesForEdo(53));

// Cent-value side-channel for the chord analyzer — avoids a circular
// import by letting jiChordAnalysis.ts pull the underlying cents
// without re-importing JI_SCALES.
for (const scale of JI_SCALES) {
  registerScaleCents(scale.name, scale.steps.map(([, c]) => c));
}

// ── Public helpers ──────────────────────────────────────────────────────

/** Family name used for all JI scales (single bucket per EDO). */
export const JI_FAMILY = JI_FAMILY_NAME;

/** Flat list of every JI scale name in catalog order. */
export const JI_SCALE_NAMES: string[] = JI_SCALES.map(s => s.name);

/** Steps for a JI scale in a given EDO, sorted ascending. */
export function getJiScaleSteps(edo: number, scaleName: string): number[] | null {
  const spec = JI_SCALES.find(s => s.name === scaleName);
  if (!spec) return null;
  return spec.steps.map(([, cents]) => centsToStep(cents, edo));
}

/** Degree labels for a JI scale, in scale order. */
export function getJiScaleDegrees(scaleName: string): string[] | null {
  const spec = JI_SCALES.find(s => s.name === scaleName);
  if (!spec) return null;
  return spec.steps.map(([deg]) => deg);
}

/** Cent values for a JI scale, in scale order.  Useful for the lattice
 *  viewer which projects exact cents onto the (3,5) lattice rather than
 *  rounding through any specific EDO grid. */
export function getJiScaleCents(scaleName: string): number[] | null {
  const spec = JI_SCALES.find(s => s.name === scaleName);
  if (!spec) return null;
  return spec.steps.map(([, c]) => c);
}
